export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const LOADING_INGREDIENTS = 'LOADING_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';

export const OPEN_INGREDIENT_MODAL = 'OPEN_INGREDIENT_MODAL';
export const INGREDIENT_ID = 'INGREDIENT_ID';

export const ADD_BUN = 'ADD_BUN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SORT_CONSTRUCTOR = 'SORT_CONSTRUCTOR';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';

export const GET_ORDER = 'GET_ORDER';
export const OPEN_ORDER_MODAL = 'OPEN_ORDER_MODAL';
export const LOADING_ORDER = 'LOADING_ORDER';
export const ERROR_ORDER = 'ERROR_ORDER';

export const REGISTRATION_USER = 'REGISTRATION_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const FORGOT_USER_PASSWORD = 'FORGOT_USER_PASSWORD';
export const RESET_USER_PASSWORD = 'RESET_USER_PASSWORD';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const LOADING_USER = 'LOADING_USER';
export const ERROR_USER = 'ERROR_USER';

export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';

export const WS_USER_CONNECTION_START = 'WS_USER_CONNECTION_START';
export const WS_USER_CONNECTION_SUCCESS = 'WS_USER_CONNECTION_SUCCESS';
export const WS_USER_CONNECTION_CLOSED = 'WS_USER_CONNECTION_CLOSED';
export const WS_USER_CONNECTION_ERROR = 'WS_USER_CONNECTION_ERROR';
export const WS_USER_GET_MESSAGE = 'WS_USER_GET_MESSAGE';
